// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type FlakyTest struct {
	TestID      string  `json:"testID"`
	TestName    string  `json:"testName"`
	PassRate    float64 `json:"passRate"`
	FailureRate float64 `json:"failureRate"`
	LastFailure *string `json:"lastFailure,omitempty"`
	RunCount    int     `json:"runCount"`
}

type Query struct {
}
