apiVersion: v1
kind: Secret
metadata:
  name: fern-mycelium-secrets
  namespace: fern-mycelium
type: Opaque
stringData:
  # Replace with your actual database URL
  DB_URL: "postgres://user:password@postgres:5432/fern_mycelium?sslmode=disable"