apiVersion: v1
kind: Service
metadata:
  name: fern-mycelium-service
  namespace: fern-mycelium
  labels:
    app: fern-mycelium
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: fern-mycelium